import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Maincontent from '../components/Maincontent'
import Footer from '../components/Footer'
import react, { useState, useEffect } from "react"
import { getList } from '../components/getList';

export default function Home() {

  const [data, setData] = useState([])
  const [error, setHasError] = useState(false)



  useEffect(() => {
    let mounted = true;
    getList()
      .then(items => {
        if (mounted) {
          setData(items)
        }
      })
    return () => mounted = false;
  }, [])



  return (
    <div>
      <Head>
        <title>9ijakids Game List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Maincontent
        data={data}

      />
      <Footer />





    </div>
  )
}
